### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [LittleDM/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report
* **Score Level**: 3/4 (Meets Expectations)
* *Comment(s)*: Your slides are well done.  They are clean and display all of the relevant data in a nice format.  I thought your inclusion of the queries in tandem with the data was a nice touch.  One thing I would have liked to see is an explanation of the actionable insights.  You summarized some data in a table that was taken from your analysis, but a description of what that data could mean for the future of the company when it comes to the quiz and home try on program would have been good.  Overall, good job!

### Criteria 2: Query Accuracy
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: All queries accurately retrieve the data intended.  Great job!

### Criteria 3: Query Formatting
* **Score Level**: 2/4 (Approaches Expectations)
* *Comment(s)*: Queries adhere to some of the rules of the style guide.  Your queries are a bit hard to read.  For instance, there are multiple keywords being used on the same line, like when you are using FROM LEFT JOIN ON.  You also didn't give each column name in the SELECT statements their own lines.  Lastly, keywords should be capitalized, but you have them lowercase.  Formatting queries, especially larger ones is very important, so being aware of that will help both you and others in the future. 

### Criteria 4: Understanding underlying concepts and terminology
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your report demonstrated an understanding of the concepts of funnel analysis.  I like that you provided some insight as to why people may be exiting the funnel at certain points in their journey, especially when doing the quiz.  Overall, good job.

### Overall Score: 13/16
Overall, you did a great job with this.  You demonstrated clear understanding of the material and developed a good looking, clean report on your findings.  All of your conclusions were supported with evidence and you gave good insight throughout your analysis.  Keep up the good work!

**Comment by LittleDM** [comment]
Hi,

First of all, thank you for the review and the comments! All noted! Especially for query formatting!
